language: node_js

before_install:
  - npm -g install

cache:
  directories:
    - "node_modules"


script:
  - cd Dashboard
  - ..//node_modules/.bin/mocha static/js/test/test.test.js --compilers js:babel-core/register