language: node_js
node_js:
 - "node"

before_install:
  - npm -g install

cache:
  directories:
    - "node_modules"


script:
  - cd Dashboard
  - mocha static/js/test/test.test.js --compilers js:babel-core/register