language: node_js

before_install:
  - npm install

cache:
  directories:
    - "node_modules"


script:
  - cd Dashboard
  - ..//node_modules/.bin/mocha static/js/test --compilers js:babel-core/register