---
version: '3.6'
services:
  db:
    build: Database
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_PASSWORD_FILE: postgres_config.txt
  
  redis:
    image: redis
    restart: always
    network_mode: "host"

  djangoapi:
    build: DjangoAPI
    restart: always
    network_mode: "host"
    ports:
      - 8000:8000
  
  confluent:
    build: Confluent
    restart: always
    network_mode: "host"
    volumes:
      - /var/confluent:/var/confluent

  cronjobs:
    build: Cron
    restart: always
    network_mode: "host"

  realtimescripts:
    build: RealTimeScripts
    restart: always
    network_mode: "host"
