---
version: '3.6'
services:
  db:
    image: postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_DB: soil
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: cDEV2017
  
  redis:
    image: redis
    restart: always
    network_mode: "host"

  djangoapi:
    build: DjangoAPI
    restart: always
    network_mode: "host"
    ports:
      - 9000:9000
  
  confluent:
    build: Confluent
    restart: always
    network_mode: "host"

  cronjobs:
    build: Cron
    restart: always
