---
version: '3.6'
services:
  db:
    image: postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_DB: soil
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: cDEV2017
  
  redis:
    image: redis
    restart: always
    network_mode: "host"

  djangoapi:
    build: DjangoAPI
    restart: always
    network_mode: "host"
    ports:
      - 8000:8000
  
  confluent:
    build: Confluent
    restart: always
    network_mode: "host"
    volumes:
      - /var/confluent:/var/confluent

  cronjobs:
    build: Cron
    restart: always
    network_mode: "host"

  realtimescripts:
    build: RealTimeScripts
    restart: always
    network_mode: "host"
